collections: 
  /:
    filter: "visibility:public"
    permalink: "/{slug}/"
    template: index
  /newsletter/:
    filter: "visibility:-public"
    permalink: "/{slug}/"
    template: index
routes:
  /account/: members/account
  /signin/: members/signin
  /signup/: public/signup
taxonomies:
  author: "/author/{slug}/"
  tag: "/tag/{slug}/"
